version: "3.3"

services:
  cobbler:
    image: petyb/cobbler-c7:v1
    privileged: true
    network_mode: host
    container_name: mycobbler
    restart: always
    environment:
      TZ: Europe/Bratislava
    volumes:
      - /apps/cobbler_settings:/etc/cobbler/settings
      - /apps/dhcp.template:/etc/cobbler/dhcp.template
